import type { Event, User } from "./types"

export const sampleEvents: Event[] = [
  {
    id: "1",
    title: "Bengaluru Tech Summit 2025",
    description:
      "The largest tech conference in Bengaluru featuring keynotes, workshops, and networking opportunities with industry leaders.",
    date: "May 15, 2025",
    time: "9:00 AM - 6:00 PM",
    location: "Bengaluru International Exhibition Centre",
    category: "Conference",
    image: "/placeholder.svg?key=qcuu8",
    price: 2500,
    isFree: false,
    attendees: 1250,
    organizer: "TechConnect Bengaluru",
    organizerId: "org1",
  },
  {
    id: "2",
    title: "AI & Machine Learning Workshop",
    description: "Hands-on workshop on the latest AI and ML technologies with practical applications and case studies.",
    date: "May 20, 2025",
    time: "10:00 AM - 4:00 PM",
    location: "Microsoft Tech Hub, Koramangala",
    category: "Workshop",
    image: "/ai-workshop.png",
    price: 1000,
    isFree: false,
    attendees: 85,
    organizer: "AI Innovators",
    organizerId: "org2",
  },
  {
    id: "3",
    title: "Web Development Meetup",
    description:
      "Monthly meetup for web developers to discuss the latest trends, tools, and best practices in web development.",
    date: "May 25, 2025",
    time: "6:00 PM - 9:00 PM",
    location: "WeWork Galaxy, Residency Road",
    category: "Meetup",
    image: "/web-development-meetup.png",
    price: 0,
    isFree: true,
    attendees: 120,
    organizer: "Bengaluru Web Devs",
    organizerId: "org1",
  },
  {
    id: "4",
    title: "Blockchain & Crypto Conference",
    description: "Explore the future of blockchain technology and cryptocurrency with experts from around the world.",
    date: "June 5, 2025",
    time: "9:30 AM - 5:30 PM",
    location: "Sheraton Grand, Raja Nagar",
    category: "Conference",
    image: "/blockchain-conference.png",
    price: 3000,
    isFree: false,
    attendees: 450,
    organizer: "Crypto Bengaluru",
    organizerId: "org3",
  },
  {
    id: "5",
    title: "Mobile App Development Workshop",
    description: "Learn to build cross-platform mobile applications using React Native and Flutter.",
    date: "June 12, 2025",
    time: "10:00 AM - 3:00 PM",
    location: "Google Developer Space, Indiranagar",
    category: "Workshop",
    image: "/placeholder.svg?height=400&width=800&query=mobile app development",
    price: 1500,
    isFree: false,
    attendees: 65,
    organizer: "App Developers Guild",
    organizerId: "org2",
  },
  {
    id: "6",
    title: "Cloud Computing Summit",
    description: "Dive deep into cloud technologies, serverless architecture, and DevOps practices.",
    date: "June 18, 2025",
    time: "9:00 AM - 6:00 PM",
    location: "Amazon Office, Embassy Tech Village",
    category: "Summit",
    image: "/placeholder.svg?height=400&width=800&query=cloud computing summit",
    price: 2000,
    isFree: false,
    attendees: 320,
    organizer: "Cloud Bengaluru",
    organizerId: "org3",
  },
  {
    id: "7",
    title: "Women in Tech Meetup",
    description: "Networking event for women in technology to share experiences, challenges, and opportunities.",
    date: "June 22, 2025",
    time: "5:00 PM - 8:00 PM",
    location: "91springboard, JP Nagar",
    category: "Meetup",
    image: "/placeholder.svg?height=400&width=800&query=women in tech event",
    price: 0,
    isFree: true,
    attendees: 95,
    organizer: "WomenTechBLR",
    organizerId: "org1",
  },
  {
    id: "8",
    title: "Startup Pitch Night",
    description: "Tech startups pitch their innovative ideas to investors and industry experts.",
    date: "June 28, 2025",
    time: "6:00 PM - 9:00 PM",
    location: "Taj MG Road",
    category: "Networking",
    image: "/placeholder.svg?height=400&width=800&query=startup pitch event",
    price: 500,
    isFree: false,
    attendees: 180,
    organizer: "Startup Bengaluru",
    organizerId: "org2",
  },
]

export const sampleUsers: User[] = [
  {
    id: "user1",
    name: "Priya Sharma",
    email: "priya@example.com",
    password: "password123",
    role: "attendee",
    registeredEvents: ["1", "3", "7"],
    profileImage: "/user-profile-1.png",
  },
  {
    id: "user2",
    name: "Rahul Mehta",
    email: "rahul@example.com",
    password: "password123",
    role: "attendee",
    registeredEvents: ["2", "4", "8"],
    profileImage: "/user-profile-2.png",
  },
  {
    id: "org1",
    name: "TechConnect Bengaluru",
    email: "techconnect@example.com",
    password: "password123",
    role: "organizer",
    registeredEvents: [],
    profileImage: "/abstract-logo.png",
    organizationName: "TechConnect Bengaluru",
    organizationDescription: "Leading tech event organizer in Bengaluru",
  },
  {
    id: "org2",
    name: "AI Innovators",
    email: "ai-innovators@example.com",
    password: "password123",
    role: "organizer",
    registeredEvents: [],
    profileImage: "/org-profile-1.png",
    organizationName: "AI Innovators",
    organizationDescription: "Specializing in AI and ML events and workshops",
  },
  {
    id: "org3",
    name: "Crypto Bengaluru",
    email: "crypto@example.com",
    password: "password123",
    role: "organizer",
    registeredEvents: [],
    profileImage: "/org-profile-2.png",
    organizationName: "Crypto Bengaluru",
    organizationDescription: "Blockchain and cryptocurrency community in Bengaluru",
  },
]
